version: "3.9"
services:

  manager:
    container_name: manager
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: manager
        SERVICE_PORT: 8080
    ports:
      - "8080:8080"

  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: worker
    deploy:
      replicas: 1
